# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161115_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='categoriees',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='posts.Rating'),
        ),
    ]
