# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20161116_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.Post'),
            preserve_default=False,
        ),
    ]
